version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - gis_5ban_network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - gis_5ban_static:/data/static/
      - gis_5ban_media:/data/media/

  django:
    image: gis_5ban_django:4
    networks:
      - gis_5ban_network
    volumes:
      - gis_5ban_static:/home/gis_5ban_1/staticfiles/
      - gis_5ban_media:/home/gis_5ban_1/media/

  mariadb:
    image: mariadb:10.5
    networks:
      - gis_5ban_network
    volumes:
      - gis_mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: password1234
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: password1234


networks:
  gis_5ban_network:

volumes:
  gis_5ban_static:
  gis_5ban_media:
  gis_mariadb:






